### ISSUE TITLE
Strip file extension from document name

### ISSUE THREAD

**Issue by Biepa** [paulgessinger/swift-paperless#102]
Hi,
I recently noticed that importing files via swift-paperless is setting the title of the document to the exact filename like "invoice.pdf". When I import the same file via Paperless itself the ".pdf" is removed.

Do you mind implementing this to be done also via the app to have a consistent behaviour?

**Comment by paulgessinger** [comment]
Might indeed be a good idea to mirror the default behavior here.

**Comment by paulgessinger** [comment]
Can you check build 80 on TestFlight @Biepa?

**Comment by Biepa** [comment]
@paulgessinger Tested. Works. Thanks a lot :+1:
