### ISSUE TITLE
Bug: error message for double ASN

### ISSUE THREAD

**Issue by Guddi11** [paulgessinger/swift-paperless#103]
Setting an ASN twice (by mistake…) does actually work but produces a meaningless error message. A more meaningful message might be good.

**Comment by paulgessinger** [comment]
I should be able to check this before even submitting the document. That way, the app won't even let you submit the document if the ASN is not unique.

**Comment by Guddi11** [comment]
Issue was solved 👍 Thanks.

However another one occurred - I provided a description via TestFlight.
