### ISSUE TITLE
Not possible to disable "Lock app with FaceID"

### ISSUE THREAD

**Issue by SoCuul** [paulgessinger/swift-paperless#106]
Whenever I toggle off the switch for faceid locking, the app doesn't save the change persistently.

This means that there is essentially no way to disable the feature, other than clearing NSUserDefaults by deleting the app.

https://github.com/paulgessinger/swift-paperless/assets/63339559/21e256fb-a255-4742-a048-958596a654a7

**Comment by paulgessinger** [comment]
I can reproduce this, thanks for reporting @SoCuul

**Comment by paulgessinger** [comment]
Can you check build 83 on TestFlight @SoCuul?

**Comment by SoCuul** [comment]
Completely fixed! 🎉
