### ISSUE TITLE
Custom headers sent with API requests

### ISSUE THREAD

**Issue by paulgessinger** [paulgessinger/swift-paperless#11]
The app should allow configuring extra headers that are sent with all API requests. This needs to be configurable before logging in, since it might be needed for obtaining a token. 

This might be useful for an installation behind CloudFlare tunnel

See
- https://github.com/paperless-ngx/paperless-ngx/discussions/3283#discussioncomment-5791608

**Comment by jimmy-ck** [comment]
I was able to test the new feature "extra headers" now on my installation: It's working! Thanks for implementing this. Issue solved from my perspective.

**Comment by DamageDoctor** [comment]
> I was able to test the new feature "extra headers" now on my installation: It's working! Thanks for implementing this. Issue solved from my perspective.

Hi @jimmy-ck . Any chance you can clarify exactly how you got it working?
When you entered the extra headers did you also include the colon in the header key?
Does your server address include https:// at the start?

![image](https://github.com/user-attachments/assets/b630725c-5b6f-47eb-829a-3526907227b2)

**Comment by DamageDoctor** [comment]
> > I was able to test the new feature "extra headers" now on my installation: It's working! Thanks for implementing this. Issue solved from my perspective.
> 
> Hi @jimmy-ck . Any chance you can clarify exactly how you got it working? When you entered the extra headers did you also include the colon in the header key? Does your server address include https:// at the start?
> 
> ![image](https://private-user-images.githubusercontent.com/19231914/355742660-b630725c-5b6f-47eb-829a-3526907227b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA1ODEsIm5iZiI6MTcyMzAyMDI4MSwicGF0aCI6Ii8xOTIzMTkxNC8zNTU3NDI2NjAtYjYzMDcyNWMtNWI2Zi00N2ViLTgyOWEtMzUyNjkwNzIyN2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA4NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZDBjNzBmYmY1NjQzNWRiODZlNWZhOTkwYTM5NDY2MzI5ODY2YjEyYjlmZGQyY2RlN2M4YTBmM2E4MjkxYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qWvtjK1HXiZ79UjLaysPXKyl8Rndyu6966BCwJpd7j8)

Please ignore. I figured it out and needed to change the access policy entry type from Allow to Service Auth. Totally missed that step.

**Comment by jimmy-ck** [comment]
Hi @DamageDoctor, no colons and address configured using https.
![IMG_7955](https://github.com/user-attachments/assets/21bd26bb-6371-4cab-a8e6-777756ab82df)
![IMG_7956](https://github.com/user-attachments/assets/5982c924-bef0-4ec1-8c56-367455d410de)

**Comment by DamageDoctor** [comment]
Yes I worked it out. Issue was actually on the Cloudflare side of my configuration but thank you for coming back so quickly!

**Comment by leepfrog-ger** [comment]
I think this may be broken when adding headers to an already existing/connected server.
Using an already connected server I've added a header with a value but the HTTP request did not contain it.
Only after logging out and configuring it on the login page the header was actually present in the request

**Comment by paulgessinger** [comment]
@leepfrog-ger I'll investigate this https://github.com/paulgessinger/swift-paperless/issues/130
