### ISSUE TITLE
Allow http networking

### ISSUE THREAD

**Issue by paulgessinger** [paulgessinger/swift-paperless#12]
Currently the all forces the requests to use https. For installations on the local network that might not be feasible, so http should be an option (but should be explicit). 

See
- https://github.com/paperless-ngx/paperless-ngx/discussions/3283#discussioncomment-5845726

**Comment by agruen** [comment]
Yes, please! I run locally (and as such don't use https... and wireguard vpn when I neee remote access!). Thanks!!

**Comment by paulgessinger** [comment]
This should now be live in Build 6 on TestFlight. Please check if this helps if you have a minute!
