### ISSUE TITLE
Add clear button to scan document name textfield

### ISSUE THREAD

**Issue by kallegrens** [paulgessinger/swift-paperless#122]
I usually rename my documents when scanning. Would love a simple clear button like in the photo. 

![image](https://github.com/user-attachments/assets/bbb5c465-965e-458b-b73e-bf261c85c9d2)

Best!

**Comment by paulgessinger** [comment]
Should be easy to add! Thanks!

**Comment by kallegrens** [comment]
Thanks! Would be a great QOL!

**Comment by paulgessinger** [comment]
@kallegrens This should be on TestFlight now.
