### ISSUE TITLE
Share/Export to Paperless App broken

### ISSUE THREAD

**Issue by xcojonny** [paulgessinger/swift-paperless#123]
Hej,

Maybe I'm the problem but I can't share a pdf with paperless from the mail app. When trying to do, the screen gets a little bit greyish for a second and then nothing happens. 

Cheers.

**Comment by paulgessinger** [comment]
Do you still get this error @xcojonny?

**Comment by xcojonny** [comment]
Hej, 

Sorry for not responding. 
Very rarely I get this issue. I think it depends on the pdf selected. But right now I can't reproduce it.

I think, it can be closed, I will give an update if it appears again.
