### ISSUE TITLE
No tag / correspondences selection in search

### ISSUE THREAD

**Issue by EugenMayer** [paulgessinger/swift-paperless#138]
Fairly new user of the app - so first thank you for providing it, open sourced!

Env: paperless-ngx 2.12.1
Ingress: k8s ingress, ngingx
User: my user is not an admin, but has read access to all perm categories (and some write)

Issue:
Being in the app, I can not see any tags in the tags facet. Is it supposed to list available tags or do I need to enter them exactly, without any auto-completion or drop down exploration?
Same for correspondents, document types and so forth

Thanks

**Comment by EugenMayer** [comment]
Checked https://github.com/paulgessinger/swift-paperless/blob/main/swift-paperless/Networking/Endpoint.swift and assuming that the URL i configured (which is actually a domain, we should change the wording, since `https://` is not allowed to be part of the string in the UI)

so `https://domain.tld/api/tags` should list tags - but it results in an 404 in my case
![image](https://github.com/user-attachments/assets/cb800a45-7dea-4978-bfcc-83e413d6d948)

So either i miss a context path or it might be that i use a paperless version that is not supported?

**Comment by EugenMayer** [comment]
After trying the api with my non-admin user i happened to noticed that the endpoint was accessible, but the list was empty. 

This is when i found out that all the entities have permissions by entity, and since i had no default view permissions applied yet, non of them where visible.

So it was an layer8 issue - sorry for the fuzz!

**Comment by paulgessinger** [comment]
Hey @EugenMayer, 
thanks for the feedback in any case. 

Indeed this scenario sounds like it would not be possible to detect this, because to the app it just looks like the logged in user simply does not have any elements to show. 

The whole permissions system server-side is a bit rough around the edges.
