### ISSUE TITLE
Allow hiding the detail view bottom bar

### ISSUE THREAD

**Issue by AndreasHD23** [paulgessinger/swift-paperless#140]
Thanks for this awesome peace of software!
Would it (pretty please) be possible to bring back fullscreen mode when viewing items?

In the latest iOS (appstore) version 1.5.1 (108) documents are overlapped by the edit window.
The new edit window is pretty nice... but I often need the pure document. Showing a receipt on my phone to a third party for example. The edit overly takes up quite some space.

Is there a chance to either:
Make it possible to swipe (hide) down the edit overlay,
make it configurable in settings if shown by default?

Again: Thanks for your effort and this amazing peace of software!

**Comment by AndreasHD23** [comment]
Thank you for taking the time to consider. Would taping the document once to show it fullscreen and tap it again to show the windows as it is right now (including edit options) maybe be more iOS intuitive?

**Comment by paulgessinger** [comment]
I'm not sure how that interacts with the gestures of the pdf view itself, for example you would want to be able to tap on links in the document itself.

**Comment by paulgessinger** [comment]
@AndreasHD23 I implemented something like this now, can you check it out on TestFlight build 111?

**Comment by sentientt** [comment]
@paulgessinger 

Tested on build 112. Personally, I find the tap to show/disable info window a bit distracting. For example, when I try to select some text and then click elsewhere to cancel the selection, the current behavior can feel unintuitive.

Here’s a suggestion for a possible flow:

1. **Click on any document in the view page:**
The document opens in full screen without displaying the info window by default
2. **Toggle the info window:**
Add a button to explicitly toggle the info window when needed
(btw, the current icon looks like a "Back to top" button. maybe change a different icon for clarity?)
3. **Tap behavior on the document:**
Tapping on the document itself should not trigger the info window to appear

In general, I think the info window should only appear when needed. Most of the time, user open a document primarily to view its content, so keeping the view clean and focused would enhance the experience.
