### ISSUE TITLE
Translation to Italian + Offer to Contribute

### ISSUE THREAD

**Issue by liuktc** [paulgessinger/swift-paperless#142]
Hi team,

Thank you for the fantastic work on this app—it's truly impressive :two_hearts: ! One feature I’d love to see added is support for the Italian language.

I’m eager to contribute by helping with the Italian translation. Could someone guide me on how I might get involved in this process? Any instructions or pointers would be greatly appreciated!

Thank you in advance for your help.

**Comment by paulgessinger** [comment]
Hey @liuktc, thanks for the offer! 

Starting with a translation would be great! The way that I've done it with other languages is to create an issue for a new version and ping people on there to help with translation on crowdin. 

I've also added Italian on crowdin now.
