### ISSUE TITLE
Support tint color (picked from the instance)

### ISSUE THREAD

**Issue by apfelnutzer** [paulgessinger/swift-paperless#143]
I don't really like that green and picked another color for the web interface. It'd be great if I could also pick a tint color for the app (or if it would take over the tint color from the web interface). Bonus: adjust the app icon accordingly. 😇

**Comment by paulgessinger** [comment]
I hear you. I think changing the app icon dynamically will not be possible, but changing the tint color might. 

On ceveat is that i can't fine tune the colors to work well with the UI, so contrast issues may happen. 

Anyway: closing this in favor of https://github.com/paulgessinger/swift-paperless/issues/90
