### ISSUE TITLE
Prevent being locked out on loading screen if connection changed

### ISSUE THREAD

**Issue by gstevenson** [paulgessinger/swift-paperless#146]
I've just migrated my paperless server which meant the machine had a new IP. When launching the app, it's unable to connect, but unless I just wasn't patient enough the connection never seems to time out and allow me to alter server settings.

Workaround was to uninstall and reinstall the app and go through onboarding again. Worked fine, but not ideal :)

**Comment by paulgessinger** [comment]
Hey @gstevenson,

Thanks for reporting this. I assume where you got stuck is this top level loading scree? You're right that if it gets stuck there you can't actually get to the log out button. 

I'll have to come up with a solution for this!
