### ISSUE TITLE
Improve description of saved view title dropdown

### ISSUE THREAD

**Issue by jradwan** [paulgessinger/swift-paperless#149]
New to the app, working great so far!

At the top of the screen in the center is a control that shows "Documents" with a dropdown arrow next to it, but tapping on it does nothing. What is that there for? The other controls up there (triple dot, #, tasks, and +) all work.

**Comment by paulgessinger** [comment]
That should let you switch between saved view. Maybe it's not obvious if you don't have any saved views. I should probably make this more descriptive

**Comment by jradwan** [comment]
Ah! Sure enough. I'm still new to Paperless as well and hadn't created any saved views yet, But once I did, that top menu works as expected. Thanks for the tip!
