### ISSUE TITLE
Multi-value saved view rule values as comma-separated lists

### ISSUE THREAD

**Issue by drBeam** [paulgessinger/swift-paperless#150]
I installed the app a while ago and if had always the problem that every few seconds i get an error message "an error has ocurred". After checking the Logs from the app i found this:

`[17.11.2024, 12:29] [API] Unable to decode response to http://example.com:8000/api/saved_views/?page_size=100000 as ListResponse<SavedView> from body <private>: Error Domain=NSCocoaErrorDomain Code=4864 UserInfo={NSDebugDescription=<private>, NSCodingPath=<private>}`

and many other entries referring to example.com. Where can i change this API URL? Most probably i'm blind but i was unable to find it in any documentation. 
I'm using Paperless-ngx 2.13.5 and paperless-swift 1.5.1

Other than that: great work!

**Comment by paulgessinger** [comment]
Hey @drBeam, the `example.com` is just masking your actual URL in the logs so that you don't need to redact it when sharing them. The actual error is a different one, where it fails to decode some response. 

Can you share more of your logs?

**Comment by paulgessinger** [comment]
More specifically, since it fails on the saved view load: could you open this same URL in a logged in browser and share the JSON response (redacted of private info of course)?

I don't have this in the logs to avoid users accidentally leaking private stuff.

**Comment by drBeam** [comment]
Hi, here is the JSON output

I checked the output and just to be on the safe side, i tried it with renaming the View "Hausrat / Strom / Gas" to "Hausrat" just to rule the spaces and slashes out, but that didn't work.

`HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 11,
    "next": null,
    "previous": null,
    "all": [
        2,
        3,
        4,
        5,
        8,
        10,
        13,
        9,
        11,
        7,
        12
    ],
    "results": [
        {
            "id": 2,
            "name": "2019",
            "show_on_dashboard": false,
            "show_in_sidebar": true,
            "sort_field": null,
            "sort_reverse": false,
            "filter_rules": [
                {
                    "rule_type": 10,
                    "value": "2019"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 3,
            "name": "2020",
            "show_on_dashboard": false,
            "show_in_sidebar": true,
            "sort_field": null,
            "sort_reverse": false,
            "filter_rules": [
                {
                    "rule_type": 10,
                    "value": "2020"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 4,
            "name": "2021",
            "show_on_dashboard": false,
            "show_in_sidebar": true,
            "sort_field": null,
            "sort_reverse": false,
            "filter_rules": [
                {
                    "rule_type": 10,
                    "value": "2021"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 5,
            "name": "2022",
            "show_on_dashboard": false,
            "show_in_sidebar": true,
            "sort_field": null,
            "sort_reverse": false,
            "filter_rules": [
                {
                    "rule_type": 10,
                    "value": "2022"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 8,
            "name": "2023",
            "show_on_dashboard": false,
            "show_in_sidebar": true,
            "sort_field": null,
            "sort_reverse": false,
            "filter_rules": [
                {
                    "rule_type": 10,
                    "value": "2023"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 10,
            "name": "Finanzen",
            "show_on_dashboard": false,
            "show_in_sidebar": true,
            "sort_field": "created",
            "sort_reverse": true,
            "filter_rules": [
                {
                    "rule_type": 22,
                    "value": "7,10,9,12,11,13,16"
                },
                {
                    "rule_type": 17,
                    "value": "20"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 13,
            "name": "Gekündigt",
            "show_on_dashboard": false,
            "show_in_sidebar": true,
            "sort_field": "created",
            "sort_reverse": true,
            "filter_rules": [
                {
                    "rule_type": 22,
                    "value": "20"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 9,
            "name": "Hausrat / Strom / Gas",
            "show_on_dashboard": false,
            "show_in_sidebar": true,
            "sort_field": "created",
            "sort_reverse": true,
            "filter_rules": [
                {
                    "rule_type": 22,
                    "value": "14,5,15"
                },
                {
                    "rule_type": 17,
                    "value": "20"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 11,
            "name": "KFZ",
            "show_on_dashboard": false,
            "show_in_sidebar": false,
            "sort_field": "created",
            "sort_reverse": true,
            "filter_rules": [
                {
                    "rule_type": 22,
                    "value": "6,12,19"
                },
                {
                    "rule_type": 17,
                    "value": "20"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 7,
            "name": "Neue Dokumente",
            "show_on_dashboard": true,
            "show_in_sidebar": true,
            "sort_field": null,
            "sort_reverse": false,
            "filter_rules": [
                {
                    "rule_type": 6,
                    "value": "21"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 12,
            "name": "Versicherungen",
            "show_on_dashboard": false,
            "show_in_sidebar": true,
            "sort_field": "created",
            "sort_reverse": true,
            "filter_rules": [
                {
                    "rule_type": 22,
                    "value": "4"
                },
                {
                    "rule_type": 17,
                    "value": "20"
                }
            ],
            "page_size": null,
            "display_mode": null,
            "display_fields": null,
            "owner": 3,
            "user_can_change": true
        }
    ]
}`

**Comment by drBeam** [comment]
Found the issue! I tested every view until the issue reappeared and this only occurs on saved views that have multiple entries in the "has tag in" field. As long as there is only one entry in the "has tag in" filter everything is fine. 
Problematic view:
![image](https://github.com/user-attachments/assets/1bb02750-89c9-4089-a89b-e87cd907c90c)
working view:
![image](https://github.com/user-attachments/assets/c868f13b-466e-4509-ad74-7b548d04e382)

**Comment by paulgessinger** [comment]
@drBeam Awesome, thanks! I can probably fix that issue!

**Comment by paulgessinger** [comment]
@drBeam ok interesting: you're doing this through the Django admin view?

I believe root cause is that the multi-value use of rule type 22 (hasTagsAny) with `14,5,15` is actually incorrect: the "correct" way that the web UI in the documents view produces is one element of the rule type 22 with a single value each. 

That's what I designed the serialization code for. For me an equivalent view looks like this in JSON:

```json
   "filter_rules": [
                {
                    "rule_type": 22,
                    "value": "55"
                },
                {
                    "rule_type": 22,
                    "value": "56"
                }
     ],
```

It seems like there's no validation logic if you do this directly in Django admin.

Now clearly, this shouldn't lead to a hard error like this, but I'm not sure if I should actually special case this and produce a "correct" representation, or simply ignore the rule in question.

**Comment by paulgessinger** [comment]
The web UI also doesn't handle multi-value rules like `11,12` correctly: when the saved view is active, the filter bar does not correctly display the selected IDs, which is if you have separate rules.

Given this, I'm somewhat inclined to make this a passthrough rule value that doesn't error the data loading, but also isn't supported for editing in the app UI.

**Comment by drBeam** [comment]
I fixed it like this now:
![image](https://github.com/user-attachments/assets/fb9dc924-38e7-452f-8186-31559bbbc031)

Thanks for your help :)
