### ISSUE TITLE
Support for Docx files

### ISSUE THREAD

**Issue by bodhi** [paulgessinger/swift-paperless#172]
Is it possible to send Word documents (Docx files) to Paperless via the iOS app? I was trying to share a Word doc from an email and couldn't find Paperless in the share sheet, nor could I select the file after I saved it to iCloud drive (it was greyed out in the file picker). I had to share it via the Paperless-ngx web UI instead.

**Comment by paulgessinger** [comment]
It's not currently supported but document input formats is on my list of features. 

See https://github.com/paulgessinger/swift-paperless/issues/139

I'm closing this in favor of the other ticket. 

There's another one for image inputs: https://github.com/paulgessinger/swift-paperless/issues/168

**Comment by bodhi** [comment]
Oops, sorry I didn't see #139. Thanks @paulgessinger, and thanks for making a great app, I use it regularly!
