### ISSUE TITLE
Option to accept an access token instead of username/password

### ISSUE THREAD

**Issue by notself** [paulgessinger/swift-paperless#21]
Is it possible to accept an access token directly instead of a username and password?

This would allow the app to work with the following Paperless setup, which I use:

- Authelia used to manage access to Paperless
- Nginx used as a reverse proxy with the `auth_request` module configured to use Authelia to authorize requests
- Paperless configured with `PAPERLESS_ENABLE_HTTP_REMOTE_USER=true` and `PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME` set to the header configured in Authelia. In my case the default `HTTP_REMOTE_USER` value
- Nginx configured to bypass Authelia for Paperless `/api` endpoints

With this setup, it means that:
- User accounts are centralised behind Authelia's user store (in my case a local LDAP server)
- User accounts in Paperless are created automatically on first access
- Paperless accounts don't have a password set
- To access the Paperless API, we can use Django's Admin interface and create a token in `admin/authtoken/tokenproxy/` for an existing user

I see the app already allows to add custom headers but at the moment, even if we manually create an `Authorization: Token xxxx` header, the login flow is still there.

**Comment by paulgessinger** [comment]
Hey @notself, yeah that's a good idea actually. 
In the end I really only save the token anyway, so one could just bypass the user/pw login flow by setting the token directly.

I'll look into this!

**Comment by notself** [comment]
Amazing. Can't wait to try this app!

**Comment by paulgessinger** [comment]
This has been on TestFlight for a while now. Did you get a chance to test it @notself?

**Comment by pyrho** [comment]
Tested with Traefik + Tinyauth, works great thanks !
