### ISSUE TITLE
Paperless with application path

### ISSUE THREAD

**Issue by Jwerfel** [paulgessinger/swift-paperless#24]
I have been trying to use the app but login was not working.  I finally got the code and it looks like the application does not handle when paperless is deployed to an application path.  

I have paperless deployed at a URL like (behind nginx):
https://myhome.myserver.com/paperless

In going through the login code I noticed the /paperless was being stripped so when the app tried to make API calls they were going to https://myhome.myserver.com/api rather than https://myhome.myserver.com/paperless/api.  I modified the login deriveUrl function so components.path += "/api/" + suffix and that allowed the login to work but then other API calls appear to be failing.  I'll look around for more places to modify in a similar manner but I wasn't sure if that was the "right" solution.

Thank you for all your hard work on this app!

**Comment by paulgessinger** [comment]
Right, that is something I definitely did not test at all. I'll try to improve this when I get back to implementing improved error handling on the login screen, which would allow me to allow debugging login issues better.

If you have a PR before then that works for you, I'm happy to merge a fix!

**Comment by paulgessinger** [comment]
I think the issue is that I'm hard setting the path here:

https://github.com/paulgessinger/swift-paperless/blob/4d626ec96fdb8251d83134ca08094fa921b4fbcb/swift-paperless/Views/LoginView.swift#L120

rather than appending. That kills the extra path component you have.

**Comment by Jwerfel** [comment]
I made the modification to the code above and that allows the login to work but the rest of the API calls to get details are still losing the application path.  Is there another easy place to find for a similar modification?

Thank you

**Comment by paulgessinger** [comment]
Yeah, the path component is not actually stored, that's true. It only stores the domain name and port in `UserDefaults`, so even with the change there, follow-up API request URLs will be ill-formed.

**Comment by paulgessinger** [comment]
I've added a fix that works in my testing. Can you grab build 22 on TestFlight and check if it works for you now?

**Comment by Jwerfel** [comment]
Thanks for making this change. I joined the TestFlight but I only see build 21, not 22. I'll try to pull the latest code and build it to see if the change works 

Thanks,
Julian

**Comment by paulgessinger** [comment]
I think due to the entitlement change it's going though some extra steps even on TestFlight. It's in the pipeline, hope it gets pushed quickly.

**Comment by Jwerfel** [comment]
I just got build 22 from TestFlight and it works with the application path.  Thank you!

**Comment by paulgessinger** [comment]
Awesome!
