### ISSUE TITLE
Login not Possible

### ISSUE THREAD

**Issue by MephistoJB** [paulgessinger/swift-paperless#25]
I am not able to login into your app. Neither on iPhone (17.0.3) nor on Mac (14.0). Unfortunately I don't get any more feedback than the white cross in the red bubble on the login button. The Path is accepted (green bubble) and I am really sure the Username and the password fits. I run Paperless-ngx (1.17.4) via docker on an unraid server. The login attempt does not appear in the Paperless logs.

Is there a way I can give you more data for analysis or a specific config I have to enable?

Thanks for your help

**Comment by MephistoJB** [comment]
Yes it is an ip Adress with a port over https (http://192.168.x.x:8000) What do I need to do to entitle the app?

**Comment by paulgessinger** [comment]
That's a code change I need to do in the app. I have build 22 in the pipeline on TestFlight that adds this (currently still in beta app review). Maybe once the build is out, can you check if this fixes the issue for you?

**Comment by MephistoJB** [comment]
Sounds great. So if I change to TestFlight this error should be gone? Shall I install the beta and give feedback?

**Comment by paulgessinger** [comment]
At least that's the idea! Build 22 should be live in TestFlight now finally.

**Comment by MephistoJB** [comment]
I just installed it via TestFlight. Unfortunately it still doesn't work.

**Comment by paulgessinger** [comment]
That's consistent with another piece of feedback I got. I'll have to investigate a bit more.

**Comment by paulgessinger** [comment]
I just tested this again with my own instance running locally under an IP address that looks just like yours, and I don't encounter any problems :/

**Comment by paulgessinger** [comment]
I just pushed build 23 to TestFlight. On that, tapping on the red x should copy the error description that was encountered. Maybe you can try to get that? Feel free to redact before you post it, obviously!

**Comment by MephistoJB** [comment]
I reale would like to do it. But now the red Cross doesn't appear. I don't get any feedback when pressing the button 😅

**Comment by paulgessinger** [comment]
Oh then I misunderstood what you are encountering. I'll add some more feedback to the login button.

**Comment by MephistoJB** [comment]
No sorry. I think I was Not clear enough here. The missing feedback of the login button is new 😂. In the last Version i got a red Cross as a Feedback. Now i dont get and Feedback.

**Comment by MephistoJB** [comment]
Thanks for the new version. I have Good News and Bad News. The good news is works now. The bad news is, it crashes now as soon as you type HTTP://
I had to copy paste the whole address at once to make it work.

**Comment by falkkrueger** [comment]
Something new about it? I would like to use the app and i have the same issue...

**Comment by Biepa** [comment]
Had this issue.
Just installed via Testflight and can login now 👍

**Comment by falkkrueger** [comment]
Works for me, tooThanks!!! Von meinem iPad gesendetAm 30.11.2023 um 21:17 schrieb Biepa ***@***.***>:﻿
Had this issue.
Just installed via Testflight and can login now 👍

**Comment by MephistoJB** [comment]
sorry for the late answer. I was not home. It works for me now, too. I would love to see this updated in the regular app store

**Comment by kumarunster** [comment]
the issue seems to be still present. just discovered your app and wanted to try it out.
When is the app updated in the App Store?

**Comment by falkkrueger** [comment]
I accidentally downloaded the app today anew from the original App Store and set it up again. It worked for me without any problems. I had to enter the IP address including http/https and including :port.Am 21.12.2023 um 10:25 schrieb Nikolai Raitsev ***@***.***>:﻿
the issue seems to be still present. just discovered your app and wanted to try it out.
When is the app updated in the App Store?

**Comment by kumarunster** [comment]
here few screenshots.
tried to type the url with IP adress or local dns name.
tried to copy paste with both.
same outcome.
the url field shows the red error and nothing happens (password field is filled, it's just iOS, that takes it out from the screenshot. Any advice what could it be? tried to restart the app inbetween as well (with wipe gesture)...

![IMG_2747](https://github.com/paulgessinger/swift-paperless/assets/2104820/d9ff6cc1-f300-4a17-bcdf-fb4467159874)
![IMG_C2191184D218-1](https://github.com/paulgessinger/swift-paperless/assets/2104820/173f97e1-ae8e-45a3-a9ee-6de995aa9df6)

**Comment by falkkrueger** [comment]
Did you really install paperless at port 9080?I think by default it is 8000Von meinem iPad gesendetAm 21.12.2023 um 10:53 schrieb Nikolai Raitsev ***@***.***>:﻿
here few screenshots.
tried to type the url with IP adress or local dns name.
tried to copy paste with both.
same outcome.
the url field shows the red error and nothing happens (password field is filled, it's just iOS, that takes it out from the screenshot. Any advice what could it be? tried to restart the app inbetween as well (with wipe gesture)...
IMG_2747.PNG (view on web)
IMG_C2191184D218-1.jpeg (view on web)

**Comment by kumarunster** [comment]
have too many apps running... paperless is on 9080 here.
<img width="666" alt="Bildschirmfoto 2023-12-21 um 11 13 54" src="https://github.com/paulgessinger/swift-paperless/assets/2104820/60ee5f01-86bf-4f60-966d-6b9ec7d2ba0c">

**Comment by falkkrueger** [comment]
Sorry, this can only be solved py Paul himself Von meinem iPad gesendetAm 21.12.2023 um 11:17 schrieb Nikolai Raitsev ***@***.***>:﻿
have too many apps running... paperless is on 9080 here.
Bildschirmfoto.2023-12-21.um.11.13.54.png (view on web)

**Comment by kumarunster** [comment]
@falkkrueger thanks for looking into this. Do you think we should reopen that issue? Any way to debug/see the cause?

**Comment by falkkrueger** [comment]
I don't know, I have no more Idea about this issue

**Comment by paulgessinger** [comment]
I'll try to get an update out on TestFlight very soon that should allow you to share logs from when this happens. Maybe I can get to the bottom of this then.
