### ISSUE TITLE
Improve error message in case document is too large

### ISSUE THREAD

**Issue by poldy79** [paulgessinger/swift-paperless#30]
In my initial setup, upload of larger files failed. The error (Failed to create Document)  message was not specific enough, so I had to dig into my nginx server logs. 

The http reponse was 413 - content too large. It would be cool if the http error code would be displayed in die error message. 

I am not a swift deveoper, nor can test any change. :-(, but I enjoy the app.

I solved the issue by configuring my nginx reverse proxy accordingly.

**Comment by paulgessinger** [comment]
#49 added a better way to present errors with details. I'm planning to make the upload screen use this mechanism.

**Comment by paulgessinger** [comment]
@poldy79 could you check if you're currently still getting this problem?

**Comment by poldy79** [comment]
Hi, 

the error message gets displayed now correctly, I am using the current released version of the app (have not found an option to display the version within the app)

The app now displays two(!) clickable banners (for about 1-2 seconds). I managed to click the banner and view thr detailed error. This helps to fix the configuration. 

![IMG_1304](https://github.com/paulgessinger/swift-paperless/assets/8228410/43716f87-2d7a-4a86-a7ce-255c4eb29de8)

Screenshot attached. 

iPhone 11pro, iOS 17.4.1

**Comment by paulgessinger** [comment]
@poldy79 Could you check if the log contains any info? That's accessible from the settings screen.

**Comment by poldy79** [comment]
It seems not. Saving logs to Files on iOS failed for me. Sending per Email worked. 
[logs.txt](https://github.com/paulgessinger/swift-paperless/files/14735564/logs.txt)

Going to „App Store“ reveals 1.0.2 as installed. 
![IMG_1306](https://github.com/paulgessinger/swift-paperless/assets/8228410/844633f0-8beb-4ab6-8bec-7508bd5a9c44)

To be clear, the initial issue is solved, would have expected to be rendered more nicely :-).

**Comment by paulgessinger** [comment]
Ah I see, I misunderstood if the error was legitimate or not.
I've now added a code path that intercepts code 413 and writes a more expressive error message.
