### ISSUE TITLE
Adding Swift-Paperless to Paperless-ngx Wiki

### ISSUE THREAD

**Issue by LuegM** [paulgessinger/swift-paperless#39]
Hey Paul,

Hope you're doing well! 
I've been using Swift-Paperless and thought it's a great fit for the Paperless-ngx 'Affiliated Projects' list (https://github.com/paperless-ngx/paperless-ngx/wiki/Affiliated-Projects). 

I believe adding your project there could help more users discover it and benefit from what you offer. 
It seems like a win-win for both communities.

What do you think? 
If you're on board with the idea, I'm happy to help out and try to get it added.

Cheers,
Michael

**Comment by paulgessinger** [comment]
Sure @LuegM!

**Comment by JensTec** [comment]
It seems to be done, so can be closed.

**Comment by LuegM** [comment]
Unfortunately, I didn't have time as I was very busy at the time. Thanks to the person who added it^.
