### ISSUE TITLE
Require Face-ID or PIN code authentication before document access / deletion

### ISSUE THREAD

**Issue by stv0g** [paulgessinger/swift-paperless#40]
I keep some pretty private data in paperless. Currently the app just allows unlimited access to those documents. Can we enforce (maybe configurable) checks via the devices PIN Code / Face-ID?

**Comment by paulgessinger** [comment]
Requiring this on a per document basis might be a bit tricky. I could imagine requiring it to delete documents, but I wonder if it might be good enough for your use case to require Face ID to unlock the app entirely. What do you think?

**Comment by JigSawFr** [comment]
> Requiring this on a per document basis might be a bit tricky. I could imagine requiring it to delete documents, but I wonder if it might be good enough for your use case to require Face ID to unlock the app entirely. What do you think?

For whole app it will be nice :)

**Comment by paulgessinger** [comment]
There's a version of this feature now in build 38 on TestFlight. @stv0g @JigSawFr
