### ISSUE TITLE
Add ability to view upload status

### ISSUE THREAD

**Issue by Itay1787** [paulgessinger/swift-paperless#41]
Hi, I noticed that when I upload I see the upload status on the right side for a few seconds and then it disappears If there is an error I don't get any info about it only if I login to the ui of paperless then I see that is a problem with  the upload of the file....

if we able to get info about the upload it we be great

**Comment by paulgessinger** [comment]
There's a version of this in build 69 on TestFlight. The tasks are now all accessible, and you can go in and check what went wrong.

If the app catches the task failing, it will also show an error message at the top.
