### ISSUE TITLE
Unable to add files with the share menu 

### ISSUE THREAD

**Issue by Itay1787** [paulgessinger/swift-paperless#42]
Hi, I was using the app today with iPad Pro 11 and when I tried to upload a file to the app through the share menu the save button wasn’t there and the other field was unusable 
See screenshot 
Don’t know if this is a problem with iPadOS or the app and don’t know if this problem is with the screen size or because I use a language that is RTL (Heb)

![image](https://github.com/paulgessinger/swift-paperless/assets/40241083/a4fbd394-cc46-4085-a961-26b197b4d0a5)

**Comment by enbyted** [comment]
This works correctly for me on iPhone 15 (standard size). However I can also reproduce the issue on iPad Pro 11 (3rd gen). iOS 17.3 in both cases. Probably a scaling issue.

Interestingly though, no matter how I scale or rotate the window (with stage manager) the right side of UI is not visible.

**Comment by paulgessinger** [comment]
@enbyted @scrapix @Itay1787 I think I have a fix for this. Can you check out build 36 on TestFlight?

**Comment by Itay1787** [comment]
> @enbyted @scrapix @Itay1787 I think I have a fix for this. Can you check out build 36 on TestFlight?

Yes! It looks like it was fixed. Thanks
