### ISSUE TITLE
Support owners & custom fields

### ISSUE THREAD

**Issue by JigSawFr** [paulgessinger/swift-paperless#45]
It can be great to support and show owners, groups and customers fields in whole app ;)
Thanks !

**Comment by Se7enair** [comment]
So far the best app for paperless I found.
But yeah, I am also missing the functionality with owners and all custom fields.

**Comment by paulgessinger** [comment]
- [ ] Ensure only documents visible to the currently logged in user are actually shown (#60)

**Comment by paulgessinger** [comment]
The ability to edit ownership and permissions os now on TestFlight and will land in `v1.5.0`. 

What's still missing is the ability to use the app with reduced permissions: right now the logged in user has to have at least the ability to see everything.
