### ISSUE TITLE
Translation to Polish

### ISSUE THREAD

**Issue by enbyted** [paulgessinger/swift-paperless#46]
Hi! Awesome app, thanks for the effort!

I’d like to translate to Polish language, can you please add stub translations to the xcstrings? 
Once you do it I can use the Localizator app to translate. 
Or, if there is another process defined I please point me to it and I’ll follow it :)

**Comment by paulgessinger** [comment]
Sounds great! I actually recently set up Crowdin for translation. I'll add polish ASAP and let you know!

**Comment by enbyted** [comment]
Ah, I didn’t see a link to crowdin (still can’t find it), but I guess it’ll be easier that way.

Happy New Year, by the way!

**Comment by paulgessinger** [comment]
@enbyted Crowdin link is here: https://crowdin.com/project/swift-paperless/invite?h=fc6b3ea7e1285d1628745547ae3dae4c1878140 . I added polish as a language.

Could you let me know if that works?

**Comment by enbyted** [comment]
The link you posted doesn’t work, but once I removed the invite part (i.e. left only crowdin/project/swift-paperless) then I had the option to join.

**Comment by paulgessinger** [comment]
Weird. I'm new to crowdin, so maybe that's how it's supposed to work. 

Any way I can see your translated strings so far, awesome!

**Comment by enbyted** [comment]
I've translated most of the strings. Let me know when there's a version of the app (testflight or otherwise) that has those, so I can search for any that don't make sense in context.

**Comment by enbyted** [comment]
I got an update of the app (via testflight) and see that you’ve built (whatever that means on crowdin) the Polish translation, but I do not see any translated strings in app.
Do I need to do anything special for the language to switch in app? Or is it not included yet?

**Comment by paulgessinger** [comment]
@enbyted sorry it's not in build 30 yet! I'll push it soon in the next build.

**Comment by JensTec** [comment]
While you are at it, I could add the Dutch translation too if you're interested. I joined the project on Crowdin.

**Comment by paulgessinger** [comment]
@JensTec Done now!

**Comment by JensTec** [comment]
Hi Paul, the Dutch translations are ready. Maybe need a bit of tweaking once shown within the app, but nothing big. Cheers.

**Comment by enbyted** [comment]
Updated Polish translations to 100%

**Comment by JensTec** [comment]
Updated Dutch translations as well. Nice to see them in the app!

**Comment by paulgessinger** [comment]
@enbyted @JensTec there are some new strings that will be included for v1.1.0. Would you be able to add translations for those in Dutch and Polish?

**Comment by JensTec** [comment]
@paulgessinger done for Dutch. Cheers.

**Comment by enbyted** [comment]
@paulgessinger done for Polish
