### ISSUE TITLE
Matching Patterns for Any Allocation of tags, etc. cannot be edited

### ISSUE THREAD

**Issue by ntrenz** [paulgessinger/swift-paperless#53]
On swift-paperless version 1.0.1, the editing of matching patterns for non-automatic matching algorithms is not possible. The creation of new, e.g. document types, with a custom (any) matching pattern is however possible. 

**Steps to reproduce:**
- on the webserver create a new document type with allocation algorithm _Any_ and set the matching pattern to any word
- go to the app and try to change the matching pattern words
- matching pattern words will not show up

**Info:** I have only tried this for document types with the matching algorithm any. But I assume that this is a generic implementation and thus applies to other allocation algorithms as well.

**Current Workaround:**
To get the input field for a custom matching pattern, you have to set the algorithm to something else, then change it back to your desired matching algorithm. Then the matching pattern input field will show up and contain your previously set words.

Editing not possible:
![IMG_5664](https://github.com/paulgessinger/swift-paperless/assets/46647854/903c6ff6-a350-4863-9ea8-fcdd134c473d)
Creation of a new document type with matching _Any_ is working with match input:
![IMG_5665](https://github.com/paulgessinger/swift-paperless/assets/46647854/5f9c0bf1-e486-4b71-b067-bd18aa615c7b)

**Comment by paulgessinger** [comment]
I can reproduce this. I think it's just the initial view that's borked somehow. I'll try to add a fix soon.

**Comment by paulgessinger** [comment]
There should be a fix in build 32 on TestFlight. Could you try if that fixes things in your end?

**Comment by ntrenz** [comment]
It works and all changes are successfully served to the backend. Thank you for the fix. When will the update be realesed for the production version of the app?
