### ISSUE TITLE
ASN number not incrementing

### ISSUE THREAD

**Issue by jphussey** [paulgessinger/swift-paperless#55]
Firstly, amazing app does pretty much everything I need and beautifully presented. 

One issue I have is if adding ASN to a document and clicking the +1 I just get 1 rather than the next increment. 

Thanks.

**Comment by paulgessinger** [comment]
I think this might be a duplicate of #47. Is this still happening on the TestFlight version?

**Comment by paulgessinger** [comment]
Ping @jphussey
