### ISSUE TITLE
Add image upload capability

### ISSUE THREAD

**Issue by peterlang-p** [paulgessinger/swift-paperless#62]
I am currently facing a challenge with importing images into the paperless system. Specifically, some of my receipts are only available in PNG format due to the export behavior of the LIDL app in my case.

**Feature Requests:**

**1. Support for JPG/PNG Import:**
Details: Modify the image import functionality to support image formats, considering cases where receipts are exported as JPG or PNG instead of PDF by certain apps like LIDL.

**2. Camera Roll Access:**
Details: Introduce a feature that allows direct access to the device's camera roll within the paperless app. This enhancement would enhance user convenience, making it easier to import images directly from the camera roll.

**3. Integration with Photos App:**
Details: Enable a seamless integration with the Photos app by implementing a share function. This would facilitate the direct sharing of images from the Photos app to the paperless system.

---
**Context:**
I really appreciate the paperless app and use it regularly as it has proven to be the best paperless app I've tried by far. Despite this, I believe that these enhancements would significantly improve the overall user experience by addressing the challenges associated with specific image formats and streamlining the import process from the camera roll.

**Note:**
This issue is being raised to suggest improvements in the image import functionality and the user interface for better compatibility with various receipt formats and enhanced convenience.

**Comment by paulgessinger** [comment]
In principle, this could use the same code path as the current camera scanning functionality, creating a PDF on the phone and then uploading that to the server.

I'll look into it!

**Comment by paulgessinger** [comment]
@peterlang-p this is now in build 61 on TestFlight. Could you check it out and let me know what you think? It should now be possible to:

- Share photos from other apps via the share sheet
- Select photos from the camera roll from the + button in the top right
- Select photos from the files app from the + button in the top right
- Import multiple inputs from files app and share sheet. If multiple images are given, they are always combined into a single PDF.

**Comment by peterlang-p** [comment]
Awesome, thank you @paulgessinger!

I just had a look and here are my findings:
- sharing from fotos app works perfectly fine
- sharing from mail app works perfectly fine
- importing images via the + button in the paperless app works fine
    -> I noticed the selection of fotos seems not to be reset. When I reopen this dialog all previously selected images are still selected and I need to deselect them first in order to create a new upload
- conversion of the image(s) to pdf is great, even if the file size is a bit large
- sharing from the LIDL app, results in "invalidAttachment"

In regards to the LIDL "issue,":
It seems that when I click on the share option in the LIDL app, instead of directly accessing the share dialog, it scrolls down and takes a screenshot of the entire receipt. Following this, the share dialog finally appears. However, when attempting to share it to paperless from this point, I encounter the "invalidAttachment" error.

By first saving the screenshot to the camera roll and then importing it from there, I'm able to successfully share the receipt to paperless without any issues.

**Comment by paulgessinger** [comment]
@peterlang-p could you share your logs from after the LIDL export fails with "invalidAttachment" (I need to improve the error output here in any case.)

**Comment by peterlang-p** [comment]
Certainly. However, unfortunately, there doesn't seem to be anything visible in the logs when I attempt to share from the LIDL app. Nevertheless, I'll send them to you via email.

**Comment by paulgessinger** [comment]
@peterlang-p I think I got it. If the image is not already written to a temporary file (like when you share a screenshot), it's passed as a different data type. I'll add a workaround for the screenshot case, maybe that works for the LIDL app as well. Stay tuned.

**Comment by paulgessinger** [comment]
@peterlang-p can you try build 65 on TestFlight?

**Comment by peterlang-p** [comment]
> @peterlang-p can you try build 65 on TestFlight?

Just gave it a try and I'm afraid I still get the "invalidAttachment" error, when trying to share from the LIDL app. But I noticed that the share dialog in the LIDL app does not have a preview compared to "normal" screenshots. Maybe that helps.
![IMG_8736](https://github.com/paulgessinger/swift-paperless/assets/86591121/7700c151-f98a-41de-a593-c125a6775620)
![IMG_8739](https://github.com/paulgessinger/swift-paperless/assets/86591121/5409fda1-1bed-4437-9240-d1ed635e4419)

**Comment by paulgessinger** [comment]
Ok @peterlang-p, I'll improve the error output next and see if we can sort out what's the issue here.

**Comment by paulgessinger** [comment]
@peterlang-p build 67 on TestFlight now has a view in case of `invalidAttachment` that allows you to export the logs from the correct process (i.e. the share extension). Could you give that a shot?

**Comment by peterlang-p** [comment]
Hey @paulgessinger 
I just tested build 67 and I cannot reproduce the error anymore. Sharing directly from the Lidl app works perfectly now. I noticed it’s imported as a png now instead of pdf but that’s totally fine for me.
Thank you so much for adding that feature.
And let me know when I can help / test something more.

**Comment by paulgessinger** [comment]
Awesome!

Indeed, I had to change the way incoming images are handled: I was converting them to a PDF right in the share extension before, but I realized that this causes the extension to go over the 120M memory limit imposed by the OS quite frequently. Instead, I'm now just POST'ing the incoming image to Paperless-ngx, which will create a PDF from it in the backend.

I believe in the end you should end up with a PDF in Paperless-ngx, right?

**Comment by peterlang-p** [comment]
![IMG_8748](https://github.com/paulgessinger/swift-paperless/assets/86591121/94af0bbc-0af0-4b07-abb0-710d1f25b3a4)

It seems to stay as a png in paperless as far as I can see, but maybe there’s a config in paperless for conversion that I might have missed. 
For me png is totally fine for these receipts, tho 🎉

**Comment by paulgessinger** [comment]
@peterlang-p I think this is just the original file name though. The OCR result pretty much has to be stored in a PDF, and indeed in my testing I'm able to select text in the document view on the right on the web interface after the processing has been completed.
