### ISSUE TITLE
Translation to Danish

### ISSUE THREAD

**Issue by paulgessinger** [paulgessinger/swift-paperless#66]

**Comment by PTST** [comment]
I have completed this translation in crowdin.  
Some of them might be wrong depending on the context in which they are used. But they should be 90% accurate, and the rest is probably easier to spot in-app

**Comment by paulgessinger** [comment]
@PTST sorry for the delay. The danish translation is now live in build 48 on [TestFlight](https://testflight.apple.com/join/bOpOdzwL).
