### ISSUE TITLE
Scrolling through documents doesn't work

### ISSUE THREAD

**Issue by xcojonny** [paulgessinger/swift-paperless#69]
Hej,

Thanks for the awesome app!

Im running Version 1.2.0 (47). 
When opening the app, only a limited number of documents are shown. When I scroll to the bottom, then no further documents are loaded. 
When I search for older documents, they are shown.  Furthermore, I get the following error on app restart:

`Der Vorgang konnte nicht abgeschlossen werden. (swift_paperless.(unknown context at $1026db650).RequestError-Fehler 0.) `

Any ideas on that?

**Comment by paulgessinger** [comment]
Hey @xcojonny,

I think the error is the same as #68. 
From a log someone else sent me it looks like it might be the document sequence throwing this error, which would explain why the documents are not loaded. 

Could you maybe also upload your logs so I can cross reference them? I'll close this issue, please refer to #68.
