### ISSUE TITLE
[APP ERROR] The operation couldn’t be completed

### ISSUE THREAD

**Issue by DrSpaldo** [paulgessinger/swift-paperless#71]
Hi, I am getting the following error in the iOS app when I open the main screen. It doesn't happen everytime but has happened a few. Not sure if I can try anything else? I believe I am on the latest iOS version & server.

`The operation couldn’t be completed. (swift_paperless.(unknown context at $101163650).RequestError error 0.)`

**Comment by paulgessinger** [comment]
I've been getting a few reports about this. My best guess is these errors were preciously also there but not reported in the UI. 

There's an issue at #68. Maybe you could attach logs from your app run when it gets the error to that issue?
