### ISSUE TITLE
Support multiple server connections

### ISSUE THREAD

**Issue by dasbaumwolltier** [paulgessinger/swift-paperless#72]
Hi, this is the best app on iOS for paperless, thank you for developing it! 

In paperless I use multiple users to separate documents into my personal space and my freelancing space. It would be nice if one could switch between users, without having to enter all the login details every time.

**Comment by paulgessinger** [comment]
I've had in my roadmap already to support logging in to multiple servers and switching between them. 

I didn't think of multiple users on the same server so far, but in principle that feature could support this as well

**Comment by paulgessinger** [comment]
@dasbaumwolltier this feature has landed on TestFlight a few weeks ago. Would be able to give it a spin?
