### ISSUE TITLE
URL invalid

### ISSUE THREAD

**Issue by SiggiKeller** [paulgessinger/swift-paperless#79]
Hello,

I run a Paperless-ngx instanz in my local network (Raspberry PI, Docker). I installed Swift Paperless on my iPad. But I can't connect. In the address field I enter http://192.168.2.80:8000 and it tells me something like "URL is invalid" (german language ;-).
At the same time I can access the paperless server with the browser on the iPad.
What do I need to do?

Thanks,
Siego

**Comment by paulgessinger** [comment]
@SiggiKeller:
Local connections using http should be supported. I've tested this, and I know people have gotten it to work. That being said, there might be something that's not working as intended that's preventing you from getting it to work. Can you share the log output from the app, maybe even after joining the TestFlight (see README on this repository)?

@knstntnb :
I believe there is a way to do this, but generally, either 

1. Adding the CA that you created the certificate with as a trusted CA system wide, or
2. Getting a Lets Encrypt certificate

are much better options to work around this in my opinion. There's so many possible issues with custom handling of self-signed certs that I don't think it's worth adding.

**Comment by SiggiKeller** [comment]
@paulgessinger:
Issue solved. Indeed it was a problem with the network access on the iPad. On my wifes iPad I got the popup you mentioned. On my iPad I could explicitely allow local network access in the app settings.
I'm a typical Linux and Windows used and not so familiar with the Apple world.

Thank you! The app looks great!
