### ISSUE TITLE
Advanced search possible?

### ISSUE THREAD

**Issue by SiggiKeller** [paulgessinger/swift-paperless#83]
A beginners question:
In the web interface I can do advanced searches like “word1 AND word2” and it will bring up documents, that contain both words. This doesn’t work in the app. Is this a general issue based on the architecture or is there a way to get advanced searches also with the app?

Thanks!

**Comment by paulgessinger** [comment]
@SiggiKeller Definitely possible. This is covered by #75, and is something I should be able to tackle soon!
