### ISSUE TITLE
Translation update for v1.2.0

### ISSUE THREAD

**Issue by paulgessinger** [paulgessinger/swift-paperless#88]
This is in preparation for the v1.2.0 App Store release

- [x] German ([Crowdin](https://crowdin.com/project/swift-paperless/de))
- [x] Danish ([Crowdin](https://crowdin.com/project/swift-paperless/da))
- [x] Dutch ([Crowdin](https://crowdin.com/project/swift-paperless/nl))
- [x] French ([Crowdin](https://crowdin.com/project/swift-paperless/fr))
- [x] Polish ([Crowdin](https://crowdin.com/project/swift-paperless/pl)

**Comment by paulgessinger** [comment]
@PTST, @enbyted, @Christophe85, @JensTec can you help out here again?

**Comment by Christophe85** [comment]
Hello @paulgessinger,

I have done it for the French Translation. Tell me if all is ok for you I am not a specialist on github.
If there is anything else to do don't hesitate.

Have a nive week.

**Comment by paulgessinger** [comment]
@Christophe85 Looks good, thanks!

**Comment by PTST** [comment]
@paulgessinger Danish is updated as well

**Comment by enbyted** [comment]
Done for the most part, I will do a second pass on all in the evening today, please don’t approve before that.
If you can check out the couple comments I left I would appreciate it.

**Comment by paulgessinger** [comment]
Thanks @enbyted! I added clarification for "Retry" and made the more tasks label a proper plural.

**Comment by enbyted** [comment]
I got the 1.2.0 on testflight, but it doesn’t have the X more tasks plural, is that not in or is there some other problem?

at any rate, the translation I made for it will fit into that menu.

**Comment by paulgessinger** [comment]
I didn't update the build yet after your last round of translations.

**Comment by paulgessinger** [comment]
@enbyted Should be live in build 76 now.

**Comment by enbyted** [comment]
Yup, got the update, looks nice, I’ll have a detailed look over the next few days

**Comment by paulgessinger** [comment]
@enbyted any last bits of feedback?

**Comment by enbyted** [comment]
@paulgessinger 
Unfortunately, I did not have too much time over the weekend, however with daily usage I did not notice anything weird in the translations.
