### ISSUE TITLE
Date decoding error

### ISSUE THREAD

**Issue by hermanmak** [paulgessinger/swift-paperless#91]
The operation couldn’t be completed. (swift_paperless.DateDecodingError error 0.)

**Comment by paulgessinger** [comment]
Oh that's interesting. 

Seems like the app fails to convert some date it received somehow. What locale and specifically date format do you have configured in the backend? 

Can you hop on the TestFlight and share logs from the settings screen.

**Comment by hermanmak** [comment]
Thanks for picking this up!

I've sent the logs via settings.

Locals not sure, do you mean what OCR languages? Eng, chi_tra, kor

**Comment by paulgessinger** [comment]
My guess is that the date format coming from your instance is somehow different than what my app expects. It might be that the backend language and date format configuration affects the API payloads.

The plan would be to check in the logs what payload it's failing to decode, and then figure out why.

**Comment by hermanmak** [comment]
So based on that date issue, I've tried changing the date format on the server to several formats and none work, I've also tried PAPERLESS_DATE_ORDER=MDY on docker too, no good.

**Comment by paulgessinger** [comment]
Where did you sent me those logs? 
If you send this from the TestFlight, I can try to figure out first of all what it is that it's trying to load. 
Then we can debug further.

**Comment by hermanmak** [comment]
Oh oops sorry I thought the logs were sent automatically! 

I clicked export logs via the app, but where is the file located? 

Thanks!

**Comment by paulgessinger** [comment]
Ah! You just have to tap again to share the logs via the share sheet. Alternatively you can use the feedback button directly

**Comment by hermanmak** [comment]
Clicking share does not export any visible file... could that be broken too?

I actually think the date field may be nil, but yea I am having issue sending and logs

**Comment by paulgessinger** [comment]
Feedback also doesn't work? I've been getting lots of feedback with logs, so I don't think it can be something super widespread. Might still be some issue I don't understand.

**Comment by hermanmak** [comment]
Thanks for your effort, actually don't know why it has no logs to export. Here is the latest

The operation couldn’t be completed. (swift_paperless.DateDecodingError error 0.)
invalidDate(string: "2024-05-13T23:38:10.546679Z")

**Comment by paulgessinger** [comment]
Hey @hermanmak, that looks like a standard ISO8601 format to me, and in principle, the app tries to decode it as such.

Could you check what the response to `https://example.com/api/saved_views/` is, where `example.com` has to be replaced with your domain? Are there any filter rules with date values?

Aside from that, I've pushed build 77 which adds some extra logging. If you manage to get the logs out of the app, I can look into this some more.

**Comment by hermanmak** [comment]
Another error now

cancelled
Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://paperless.hermanmak.dev/api/document_types/?page_size=100000, NSErrorFailingURLKey=https://paperless.hermanmak.dev/api/document_types/?page_size=100000, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <C1E43B14-6C93-49AB-9A6C-950EC46F0B44>.<20>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <C1E43B14-6C93-49AB-9A6C-950EC46F0B44>.<20>, NSLocalizedDescription=cancelled}

**Comment by paulgessinger** [comment]
This is only in the log right? If it doesn't show up in the top of the app, these errors are not an issue.

**Comment by hermanmak** [comment]
Yes the only log.. just this one and the original with the date string

**Comment by paulgessinger** [comment]
Ok! Can you share the full log with me?

**Comment by hermanmak** [comment]
Was my logs enough to debug?

**Comment by paulgessinger** [comment]
I haven't. 
It seems to be hitting my custom date parsing chain, but this format should be supported and works in my test.

**Comment by paulgessinger** [comment]
I have to say I'm stumped. I've added another test where I include this exact date string, and it decodes just fine...

@hermanmak can you:

- Get me the (redacted) JSON response from your `http://example.com/api/documents/` endpoint?
- Can you tell me what your local iPhone locale is (language, date format etc)?
- Can you tell me what the language settings in Paperless-ngx (from the settings screen on the web ui)?

**Comment by jacobtomlinson** [comment]
I am seeing the same error when initially launching the app.

```
The operation couldn’t be completed. (swift_paperless.DateDecodingError error 0.)

invalidDate(string: "2024-01-19T13:35:06.557811Z")
```

**Comment by hermanmak** [comment]
Let me try to grab more logs later in the day

-herman

**Comment by paulgessinger** [comment]
@jacobtomlinson could you try to grab the JSON content that comes from, say, documents api endpoint?

**Comment by jacobtomlinson** [comment]
Sure, here's the contents of the `/api/documents/` endpoint. I've redacted the titles, file contents and filenames.

[paperless-redacted.json](https://github.com/user-attachments/files/15786595/paperless-redacted.json)

**Comment by paulgessinger** [comment]
Thanks @jacobtomlinson.

This dump decodes perfectly fine on my machine, also when setting the locale to UK.

No idea what could be causing this, to be honest.

**Comment by paulgessinger** [comment]
Ok I have one other thing to try: I was using the ISO8601 formatter in a slightly non standard way, and then tried to catch decode failures using custom format string. **But**: apparently these format strings are possibly affected by locale. 

I'll upload a TestFlight build as soon as I can (waiting for approval) that tries a slightly different approach.

**Comment by paulgessinger** [comment]
@jacobtomlinson @hermanmak could you try build 88 on TestFlight when you get a chance?

**Comment by jacobtomlinson** [comment]
Yup that solved it for me. Thanks @paulgessinger!

**Comment by hermanmak** [comment]
Me too! Thanks!

-herman

**Comment by paulgessinger** [comment]
I'll ship this to the App Store as soon as I can
