### ISSUE TITLE
Unable to get API and backend version: X-Version not available

### ISSUE THREAD

**Issue by MrBogger** [paulgessinger/swift-paperless#97]
Good morning,
Recently installed Paperless-ngx 2.8.6 which is now up and running. Downloaded Swift Paperless 1.1.1 this morning and set up Paperless behind IIS Reverse Proxy on Windows Server 2022 21H2 through Docker. Browser Web Version working with no issues on http:// or https://. I have also downloaded PaperParrot & Less Paper and they both seem to be communicating with my Paperless Server.

Swift-Paperless logs into my Paperless instance ok with Super User access but any time I try and do something, it says:
 "An Unexpected Error occurred". "The operation couldn't be completed. (swift_paperless.(unknown context at $100fa9190).RequestError error 0.) .

Reading through the logs there seems to be a "Unable to get API and backend version: X-Version not available" error which occurs at each App startup. 

I've attached the logs from Swift-Paperless below along with Docker Configuration. There are no corresponding Log Entries from Paperless-ngx when the error occurs on the iOS App. Please let me know if there's any further information you need. Thanks for your efforts on the app by the way too.

[Docker Version.txt](https://github.com/paulgessinger/swift-paperless/files/15383935/Docker.Version.txt)
[docker-compose.env.txt](https://github.com/paulgessinger/swift-paperless/files/15383936/docker-compose.env.txt)
[docker-compose.yml.txt](https://github.com/paulgessinger/swift-paperless/files/15383937/docker-compose.yml.txt)
[Swift-Paperless http log.txt](https://github.com/paulgessinger/swift-paperless/files/15383938/Swift-Paperless.http.log.txt)
[Swift-Paperless https log.txt](https://github.com/paulgessinger/swift-paperless/files/15383939/Swift-Paperless.https.log.txt)
.

**Comment by paulgessinger** [comment]
Hey! Would you mind trying this on the TestFlight beta, and sending logs from there?

The version problem is unexpected, this is usually some issue with the networking in the app, the decoding error could be related or could be something else.

**Comment by MrBogger** [comment]
Hey Paul,  

Seems to be the same situation with TestFlight. Works on LAN but not WAN. 

I did some digging through Firefox and eventually found I didn't have the WebSocket package installed in IIS as my Radarr was working but coming up with ws:// and wss:// errors. Since installing the WebSockets, Radarr is connecting fine through the proxy but still errors on Paperless.
   *  [signalR] Information: WebSocket connected to wss://xxx.xxx.org/radarr/signalr/messages?access_token
   
   *  Firefox can’t establish a connection to the server at wss://xxx.xxx.org/paperless/ws/status/.

However, I still get the same error from using Firefox on the PC running Docker so there may be an underlying issue with either my Docker install or Paperless itself:
   *  Firefox can’t establish a connection to the server at ws://localhost:8050/paperless/ws/status/.


[Swift-Paperless Test Flight.txt](https://github.com/paulgessinger/swift-paperless/files/15390590/Swift-Paperless.Test.Flight.txt)
(First attempted login was WAN and next login was LAN)

[Firefox Console LAN.txt](https://github.com/paulgessinger/swift-paperless/files/15390824/Firefox.Console.LAN.txt)
[Firefox Console WAN.txt](https://github.com/paulgessinger/swift-paperless/files/15390825/Firefox.Console.WAN.txt)

**Comment by paulgessinger** [comment]
Ok, managed to test this now, and I think I might have a fix. Can you update your TestFlight install to build 78, and try again?

**Comment by MrBogger** [comment]
Hi Paul,

Working 100% through domain and proxy with sub path. Thank you. 

[logs.txt](https://github.com/paulgessinger/swift-paperless/files/15392108/logs.txt)
